version: "2"

services:
  currency_api:
    container_name: currency_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
      - ./db:/db
    ports:
      - "8010:8010"
    environment:
      - SERVER_PORT=8010
      - ./docker-entrypoint-initdb.d/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always